### ISSUE TITLE
Which versions of Node do you intend to support?

### ISSUE THREAD

**Issue by jonathantneal** [MattDiMu/postcss-replace-overflow-wrap#1]
I see you have [tests](https://github.com/MattDiMu/postcss-replace-overflow-wrap/blob/master/.travis.yml) for Node v5, v4, and v0.12. The current LTS is v6. I would recommend you support this one and take advantage of [function bodies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Function_body) and [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters).

You could be doubly safe and support LTS v4, but I would highly recommend dropping support for v0.12.

To understand the difference in feature sets between v6, v4, and v0.12, please see: https://kangax.github.io/compat-table/es6/#node65

**Comment by Semigradsky** [comment]
Node v4 will be supported until 1 April, 2018. Drop v4 support isn't very good idea.

**Comment by jonathantneal** [comment]
Great. Drop 0.12 and keep v4 and possibly add `stable` to .travis.yml?

FYI, my PR does not interfere with this.
