### ISSUE TITLE
No need to document 'copy' option

### ISSUE THREAD

**Issue by jonathantneal** [MattDiMu/postcss-replace-overflow-wrap#4]
No need to test for **copy** either, because it doesn’t exist. The default option is **replace**, but any other option becomes **copy before**, effectively.

**Comment by MattDiMu** [comment]
Thx for reviewing and yes, you're right. The implementation isn't smooth, as any passed method results a **copy before** behavior. I should change this to a more defensive approach, where invalid options result in the default **replace** behavior.

Btw, do you see any valid use case for a **copy after**  method?
