### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by Semigradsky** [MattDiMu/postcss-replace-overflow-wrap#9]
**Thanks for your PostCSS plugin!**

As you probably know, PostCSS 8 was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration).

**Comment by MattDiMu** [comment]
@Semigradsky Thx for the hint. Version 4.0.0+ should support PostCSS 8:
https://www.npmjs.com/package/postcss-replace-overflow-wrap?activeTab=versions
